name: Deploy Frontend on Vercel

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      BACKEND_URL: ${{ secrets.BACKEND_URL }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
      env:
        VITE_API_URL: ${{ env.BACKEND_URL }}

    - name: Deploy to Vercel
      run: |
        npx vercel deploy --prod \
          --token $VERCEL_TOKEN \
          --org-id $VERCEL_ORG_ID \
          --project-id $VERCEL_PROJECT_ID
